<script type='text/javascript' id='<cms:show k_site_link />quick-js'></script>
<script type='text/javascript' src='<cms:show k_site_link />js/jquery-2.2.3.min.js'></script>
<script type='text/javascript' src='<cms:show k_site_link />js/bootstrap.min.js'></script>
<script type='text/javascript' src='<cms:show k_site_link />js/jquery.flexslider-min.js'></script>
<script type='text/javascript' src='<cms:show k_site_link />js/jquery.swipebox.min.js'></script>
<script type='text/javascript' src='<cms:show k_site_link />js/jquery.isotope.min.js'></script>
<script type='text/javascript' src='<cms:show k_site_link />js/jquery.appear.js'></script>
<script type='text/javascript' src='<cms:show k_site_link />js/jquery.ui.core.min.js'></script>
<script type='text/javascript' src='<cms:show k_site_link />js/jquery.ui.datepicker.min.js'></script>
<script type='text/javascript' src='<cms:show k_site_link />js/jquery.validate.min.js'></script>
<script type='text/javascript' src='<cms:show k_site_link />js/jquery.form.js'></script>
<script type='text/javascript' src='<cms:show k_site_link />js/jquery.autosize.min.js'></script>
<script type='text/javascript' src='<cms:show k_site_link />js/jquery.meanmenu.min.js'></script>
<script type='text/javascript' src='<cms:show k_site_link />js/jquery.velocity.min.js'></script>
<script type='text/javascript' src='<cms:show k_site_link />js/jquery-twitterFetcher.js'></script>
<script type='text/javascript' src='<cms:show k_site_link />js/respond.min.js'></script>
<script type='text/javascript' src='<cms:show k_site_link />js/jquery-migrate-1.2.1.min.js'></script>
<script type='text/javascript' src='<cms:show k_site_link />js/custom.js'></script>
<script type='text/javascript' src='<cms:show k_site_link />js/slick.js'></script>
<script type='text/javascript' src='<cms:show k_site_link />js/main.js'></script>